# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExpenseItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, expense_type: str=None, amount: float=None, _date: date=None, request_name: str=None):  # noqa: E501
        """ExpenseItem - a model defined in Swagger

        :param name: The name of this ExpenseItem.  # noqa: E501
        :type name: str
        :param expense_type: The expense_type of this ExpenseItem.  # noqa: E501
        :type expense_type: str
        :param amount: The amount of this ExpenseItem.  # noqa: E501
        :type amount: float
        :param _date: The _date of this ExpenseItem.  # noqa: E501
        :type _date: date
        :param request_name: The request_name of this ExpenseItem.  # noqa: E501
        :type request_name: str
        """
        self.swagger_types = {
            'name': str,
            'expense_type': str,
            'amount': float,
            '_date': date,
            'request_name': str
        }

        self.attribute_map = {
            'name': 'name',
            'expense_type': 'expenseType',
            'amount': 'amount',
            '_date': 'date',
            'request_name': 'requestName'
        }
        self._name = name
        self._expense_type = expense_type
        self._amount = amount
        self.__date = _date
        self._request_name = request_name

    @classmethod
    def from_dict(cls, dikt) -> 'ExpenseItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpenseItem of this ExpenseItem.  # noqa: E501
        :rtype: ExpenseItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ExpenseItem.


        :return: The name of this ExpenseItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ExpenseItem.


        :param name: The name of this ExpenseItem.
        :type name: str
        """

        self._name = name

    @property
    def expense_type(self) -> str:
        """Gets the expense_type of this ExpenseItem.


        :return: The expense_type of this ExpenseItem.
        :rtype: str
        """
        return self._expense_type

    @expense_type.setter
    def expense_type(self, expense_type: str):
        """Sets the expense_type of this ExpenseItem.


        :param expense_type: The expense_type of this ExpenseItem.
        :type expense_type: str
        """

        self._expense_type = expense_type

    @property
    def amount(self) -> float:
        """Gets the amount of this ExpenseItem.


        :return: The amount of this ExpenseItem.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this ExpenseItem.


        :param amount: The amount of this ExpenseItem.
        :type amount: float
        """

        self._amount = amount

    @property
    def _date(self) -> date:
        """Gets the _date of this ExpenseItem.


        :return: The _date of this ExpenseItem.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this ExpenseItem.


        :param _date: The _date of this ExpenseItem.
        :type _date: date
        """

        self.__date = _date

    @property
    def request_name(self) -> str:
        """Gets the request_name of this ExpenseItem.


        :return: The request_name of this ExpenseItem.
        :rtype: str
        """
        return self._request_name

    @request_name.setter
    def request_name(self, request_name: str):
        """Sets the request_name of this ExpenseItem.


        :param request_name: The request_name of this ExpenseItem.
        :type request_name: str
        """

        self._request_name = request_name
